package com.timcritt.tfg.infrastructure.persistence;

import com.timcritt.tfg.domain.model.MaterialReference;
import com.timcritt.tfg.infrastructure.persistence.jpa.MaterialReferenceJpaEntity;

public final class MaterialReferenceEntityMapper {
    private MaterialReferenceEntityMapper() {}

    public static MaterialReference toDomain(MaterialReferenceJpaEntity entity) {
        if (entity == null) {
            return null;
        }
        return new MaterialReference(
                entity.getId(),
                entity.getMaterialId(),
                entity.getName(),
                entity.getDescription(),
                entity.getPart1Title(),
                entity.getPart2Title(),
                entity.getAssignedToRole()
        );
    }

    public static MaterialReferenceJpaEntity toEntity(MaterialReference domain) {
        if (domain == null) {
            return null;
        }
        // For inserts, the ID must be generated by the database (IDENTITY).
        // For updates, we update the existing managed entity instance (see command adapter).
        return new MaterialReferenceJpaEntity(
                domain.getMaterialId(),
                domain.getName(),
                domain.getDescription(),
                domain.getPart1Title(),
                domain.getPart2Title(),
                domain.getAssignedToRole()
        );
    }
}
